// Package store loads and saves domains.json and holds the rules every domain
// follows.
package store

import (
	"bytes"
	"cmp"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"net/netip"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"github.com/sangdth/lcd/internal/fsutil"
)

// NamePattern matches a valid name, without anchors. The root script runs it
// through grep -E -x, so it must mean the same in POSIX ERE and in Go's RE2.
const NamePattern = `[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)*\.local`

// MaxNameLen is the longest name DNS allows.
const MaxNameLen = 253

// The own block: loopback addresses lcd hands out, one project each.
const (
	OwnPrefix = "127.0.1."
	OwnFirst  = 1
	OwnLast   = 50
)

// ProxyPort is where Caddy listens. A domain forwards to any other port.
const ProxyPort = 80

// Version is the domains.json format this build reads and writes.
const Version = 1

// GeneratedHeader is the first line of every file lcd generates from
// domains.json.
const GeneratedHeader = "# Generated by lcd from domains.json. Edits are overwritten.\n"

// ErrBlockFull means every own address is taken.
var ErrBlockFull = fmt.Errorf("all %d own addresses are taken", OwnLast-OwnFirst+1)

var (
	nameRE   = regexp.MustCompile(`^(?:` + NamePattern + `)$`)
	loopback = netip.MustParsePrefix("127.0.0.0/8")
)

// Domain is one row: a name, the address it resolves to, an optional port
// Caddy forwards to, and whether it is on.
type Domain struct {
	Name    string `json:"name"`
	Address string `json:"address"`
	Port    int    `json:"port,omitempty"`
	Enabled bool   `json:"enabled"`
}

// The fields a FieldError can concern.
const (
	FieldName    = "name"
	FieldAddress = "address"
	FieldPort    = "port"
)

// FieldError is a rule a domain breaks, tied to the form field it concerns.
type FieldError struct {
	Field string
	Msg   string
}

func (e *FieldError) Error() string { return e.Msg }

func fieldErr(field, msg string) error { return &FieldError{Field: field, Msg: msg} }

// ValidateName checks a name: lowercase labels of a-z, 0-9 and inner '-',
// ending in .local, with at least one label before it.
func ValidateName(name string) error {
	switch {
	case name == "":
		return fieldErr(FieldName, "name is empty")
	case len(name) > MaxNameLen:
		return fieldErr(FieldName, fmt.Sprintf("name is longer than %d characters", MaxNameLen))
	case strings.ToLower(name) != name:
		return fieldErr(FieldName, "name must be lowercase")
	case !strings.HasSuffix(name, ".local"):
		return fieldErr(FieldName, "name must end in .local")
	case name == ".local":
		return fieldErr(FieldName, "name needs a label before .local")
	case !nameRE.MatchString(name):
		return fieldErr(FieldName, "name may use only a-z, 0-9 and '-' inside labels of 1-63 characters")
	}
	return nil
}

// ValidateAddress checks an address: IPv4 inside 127.0.0.0/8, written the
// usual way.
func ValidateAddress(addr string) error {
	a, err := netip.ParseAddr(addr)
	if err != nil || !a.Is4() || !loopback.Contains(a) || a.String() != addr {
		return fieldErr(FieldAddress, "address must be an IPv4 address in 127.0.0.0/8, like 127.0.1.3")
	}
	return nil
}

// ValidatePort checks a port: 0 means none, else 1-65535 except Caddy's own.
func ValidatePort(port int) error {
	switch {
	case port == 0:
		return nil
	case port < 1 || port > 65535:
		return fieldErr(FieldPort, "port must be between 1 and 65535")
	case port == ProxyPort:
		return fieldErr(FieldPort, "port 80 is where Caddy listens; use the app's own port")
	}
	return nil
}

// ParsePort reads the port field. Empty means no port.
func ParsePort(s string) (int, error) {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0, nil
	}
	n, err := strconv.Atoi(s)
	if err != nil {
		return 0, fieldErr(FieldPort, "port must be a number")
	}
	if n < 1 || n > 65535 {
		return 0, fieldErr(FieldPort, "port must be between 1 and 65535")
	}
	if err := ValidatePort(n); err != nil {
		return 0, err
	}
	return n, nil
}

// OwnAddress returns the i-th address of the own block.
func OwnAddress(i int) string { return OwnPrefix + strconv.Itoa(i) }

// IsOwn reports whether addr is in the own block.
func IsOwn(addr string) bool {
	rest, ok := strings.CutPrefix(addr, OwnPrefix)
	if !ok {
		return false
	}
	n, err := strconv.Atoi(rest)
	return err == nil && n >= OwnFirst && n <= OwnLast && strconv.Itoa(n) == rest
}

// Project returns the last two labels of a name: crm.local for test.crm.local.
func Project(name string) string {
	labels := strings.Split(name, ".")
	if len(labels) <= 2 {
		return name
	}
	return strings.Join(labels[len(labels)-2:], ".")
}

// Parent returns the listed domain whose name is the longest proper suffix
// of name: test.crm.local for a.test.crm.local when both it and crm.local
// are listed.
func Parent(domains []Domain, name string) (Domain, bool) {
	var parent Domain
	found := false
	for _, d := range domains {
		if strings.HasSuffix(name, "."+d.Name) && (!found || len(d.Name) > len(parent.Name)) {
			parent, found = d, true
		}
	}
	return parent, found
}

// NextFree returns the lowest own address no domain uses, on or off.
func NextFree(domains []Domain) (string, error) {
	used := make(map[string]bool, len(domains))
	for _, d := range domains {
		used[d.Address] = true
	}
	for i := OwnFirst; i <= OwnLast; i++ {
		if a := OwnAddress(i); !used[a] {
			return a, nil
		}
	}
	return "", ErrBlockFull
}

// Sort returns the domains ordered by their labels read right to left, so a
// parent comes right before its subdomains and each project stays together.
func Sort(domains []Domain) []Domain {
	s := slices.Clone(domains)
	slices.SortFunc(s, func(a, b Domain) int { return compareNames(a.Name, b.Name) })
	return s
}

func compareNames(a, b string) int {
	la, lb := strings.Split(a, "."), strings.Split(b, ".")
	for i, j := len(la)-1, len(lb)-1; i >= 0 && j >= 0; i, j = i-1, j-1 {
		if c := strings.Compare(la[i], lb[j]); c != 0 {
			return c
		}
	}
	return cmp.Compare(len(la), len(lb))
}

// Validate checks every domain and the rules between them, in list order.
func Validate(domains []Domain) error {
	for i, d := range domains {
		if err := check(domains[:i], d); err != nil {
			return fmt.Errorf("%q: %w", d.Name, err)
		}
	}
	return nil
}

// check validates d on its own and against the others: names are unique, and
// an own address belongs to one project.
func check(others []Domain, d Domain) error {
	if err := ValidateName(d.Name); err != nil {
		return err
	}
	if err := ValidateAddress(d.Address); err != nil {
		return err
	}
	if err := ValidatePort(d.Port); err != nil {
		return err
	}
	for _, o := range others {
		if o.Name == d.Name {
			return fieldErr(FieldName, d.Name+" is already listed")
		}
	}
	if IsOwn(d.Address) {
		for _, o := range others {
			if o.Address == d.Address && Project(o.Name) != Project(d.Name) {
				return fieldErr(FieldAddress, d.Address+" belongs to "+o.Name)
			}
		}
	}
	return nil
}

// Add returns the list with d added, or the rule d breaks.
func Add(domains []Domain, d Domain) ([]Domain, error) {
	if err := check(domains, d); err != nil {
		return nil, err
	}
	return Sort(append(slices.Clone(domains), d)), nil
}

// Update returns the list with the domain called name replaced by d, or the
// rule d breaks. Other domains never change.
func Update(domains []Domain, name string, d Domain) ([]Domain, error) {
	i := slices.IndexFunc(domains, func(x Domain) bool { return x.Name == name })
	if i < 0 {
		return nil, fmt.Errorf("%s is not listed", name)
	}
	others := slices.Delete(slices.Clone(domains), i, i+1)
	if err := check(others, d); err != nil {
		return nil, err
	}
	return Sort(append(others, d)), nil
}

// Remove returns the list without the domain called name.
func Remove(domains []Domain, name string) ([]Domain, error) {
	i := slices.IndexFunc(domains, func(x Domain) bool { return x.Name == name })
	if i < 0 {
		return nil, fmt.Errorf("%s is not listed", name)
	}
	return slices.Delete(slices.Clone(domains), i, i+1), nil
}

// Toggle returns the list with the domain called name switched on or off.
func Toggle(domains []Domain, name string) ([]Domain, error) {
	i := slices.IndexFunc(domains, func(x Domain) bool { return x.Name == name })
	if i < 0 {
		return nil, fmt.Errorf("%s is not listed", name)
	}
	s := slices.Clone(domains)
	s[i].Enabled = !s[i].Enabled
	return s, nil
}

type file struct {
	Version int      `json:"version"`
	Domains []Domain `json:"domains"`
}

// Load reads and checks domains.json. A missing file is an empty list.
func Load(path string) ([]Domain, error) {
	data, err := os.ReadFile(path) //nolint:gosec // G304: the path comes from paths.Paths
	if errors.Is(err, fs.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read domains: %w", err)
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	var f file
	if err := dec.Decode(&f); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if f.Version != Version {
		return nil, fmt.Errorf("%s: format version %d, this lcd reads version %d", path, f.Version, Version)
	}
	if err := Validate(f.Domains); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return Sort(f.Domains), nil
}

// Save checks the domains and writes them to path, sorted, through a
// temporary file.
func Save(path string, domains []Domain) error {
	if err := Validate(domains); err != nil {
		return err
	}
	sorted := Sort(domains)
	if sorted == nil {
		sorted = []Domain{}
	}
	data, err := json.MarshalIndent(file{Version: Version, Domains: sorted}, "", "  ")
	if err != nil {
		return fmt.Errorf("encode domains: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil { //nolint:gosec // G301: ~/.config/lcd holds no secrets
		return fmt.Errorf("create %s: %w", filepath.Dir(path), err)
	}
	if _, err := fsutil.WriteFile(path, append(data, '\n'), 0o644); err != nil {
		return fmt.Errorf("save domains: %w", err)
	}
	return nil
}
